[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pylint.main]
generated-members = ["cv2"]

[tool.pylint.'MESSAGES CONTROL']
disable = '''
        missing-module-docstring,
        missing-class-docstring,
        missing-function-docstring,
        broad-exception-caught,
        broad-exception-raised,
        logging-fstring-interpolation,
        too-many-arguments,
        too-many-positional-arguments,
        import-outside-toplevel,
        '''

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict = true

[tool.isort]
profile = "black"
