name: Lint, Test and Check formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_test:
    name: Run Ruff (lint & format), Mypy, Pytest and Isort
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Run Ruff (lint)
        run: python -m ruff check src/pimpmyrice tests

      - name: Run Mypy
        run: python -m mypy src/pimpmyrice tests

      - name: Run Pytest
        run: python -m pytest --junitxml=reports/test-results.xml

      - name: Run Ruff (format)
        run: python -m ruff format --check --diff src/pimpmyrice tests

      - name: Run Isort
        run: python -m isort --check --diff src/pimpmyrice tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/test-results.xml

